# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

resources:
  repositories:
  - repository: Bicep-Modules
    type: git
    name: ContosoHotels/Bicep-Modules
    ref: Dev

trigger:
- none

parameters:
- name: environment
  displayName: 'Environment to deploy'
  type: string
  default: Integration
  values:
  - Integration
  - Production
  - PreProd

variables:
- ${{ if eq(parameters.environment, 'Integration') }}:
  - template: container-monitoring-integration.variables.yml
- ${{ if eq(parameters.environment, 'Production') }}:
  - template: container-monitoring-production.variables.yml
- ${{ if eq(parameters.environment, 'PreProd') }}:
  - template: container-monitoring-preprod.variables.yml


stages:
- stage: Lint
  jobs: 
  - job: LintCode
    displayName: Lint code
    steps:
    
       - checkout: self
       - checkout: Bicep-Modules

       - task: CopyFiles@2
         displayName: 'Copy PowerShell scripts'
         inputs:
           SourceFolder: '$(Agent.BuildDirectory)/s/Bicep-Modules'
           Contents: '*'
           TargetFolder: '$(Agent.BuildDirectory)/s/ContainerMonitoring/.bicep'
           