# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

resources:
  repositories:
  - repository: bicep
    type: git
    name: ContosoHotels/Bicep-Modules
    ref: bicepModules_aks

trigger:
- none

parameters:
- name: environment
  displayName: 'Environment to deploy'
  type: string
  default: Integration
  values:
  - Integration
  - Production
  - PreProd

- name: enableAADProfile
  displayName: 'Enable AAD profile for AKS cluster'
  type: string
  default: false
  values:
  - false
  - true


variables:
- ${{ if eq(parameters.environment, 'Integration') }}:
  - template: container-monitoring-integration.variables.yml
- ${{ if eq(parameters.environment, 'Production') }}:
  - template: container-monitoring-production.variables.yml
- ${{ if eq(parameters.environment, 'PreProd') }}:
  - template: container-monitoring-preprod.variables.yml

  - name: aadProfile
    ${{ if eq( parameters.enableAADProfile, 'true') }}:
      value: 'true'
    ${{ if eq( parameters.enableAADProfile, 'false') }}:
      value: 'false'

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy Container Monitoring
    pool: 
      vmImage: ubuntu-latest
    
    variables:
    - template: container-monitoring-variables.yml
    
    steps:
    - checkout: self
    - checkout: bicep

    - task: CopyFiles@2
      displayName: 'Copy bicep modules'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/Bicep-Modules'
        Contents: '**/modules/**'
        TargetFolder: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/bicep'

    - script: |
        az bicep build --file $(Build.SourcesDirectory)/$(Build.Repository.Name)/bicep/main.bicep
      displayName: 'Lint'

    - task: AzureKeyVault@1
      displayName: Load Secrets
      inputs:
        azureSubscription: '$(stagingSubscriptionEndpoint)'
        KeyVaultName: '$(stagingKeyVaultName)'
        SecretsFilter: 'ContosoSH360ClusterSPClientId, ContosoSH360ClusterSPClientSecret, ContosoSH360ClusterSPObjectId, chVmAdminPassword, chVmAdminUser '

    - task: AzurePowerShell@4
      name: RunWhatIf
      displayName: Run what-if
      inputs:
        azurePowerShellVersion: LatestVersion
        azureSubscription:  $(azureSubscriptionEndpoint)
        ScriptType: InlineScript
        Inline: |
          $subscriptionId = (Get-AzContext).Subscription.Id
          New-AzSubscriptionDeployment -Whatif -Location '$(location)' -TemplateFile '$(Build.SourcesDirectory)/$(Build.Repository.Name)/bicep/main.bicep' -TemplateParameterObject @{
            subscriptionId = $subscriptionId
            location = '$(location)'
            prefix = '$(prefix)'
            contosoSH360ClusterResourceGroupName = '$(resourceGroupName)'
            opsResourceGroupName = '$(workspaceResourceGroupName)'
            logAnalyticsWorkspaceName = '$(workspaceName)'
            workspaceSkuName = '$(workspaceSkuName)'
            montioredClusterName = '$(AKSName)'
            nonMontioredClusterName = '$(NonMonitoredAKSName)'
            adminUser = '$(chVmAdminUser)'
            adminPassword = '$(chVmAdminPassword)'
            servicePrincipalClientId = '$(ContosoSH360ClusterSPClientId)'
            servicePrincipalClientSecret = '$(ContosoSH360ClusterSPClientSecret)'
            agentVMSize = '$(agentVMSize)'
            aksClusterNetworkPlugin = '$(aksClusterNetworkPlugin)'
            aksClusterNetworkPolicy = '$(aksClusterNetworkPolicy)'
            aksClusterServiceCidr = '$(aksClusterServiceCidr)'
            aksClusterDockerBridgeCidr = '$(aksClusterDockerBridgeCidr)'
            clusterVersion = '$(clusterVersion)'
            aadProfile = '${{ variables.aadProfile }}'
          } -Verbose

    - task: AzurePowerShell@4
      displayName: 'Create resources'
      condition: not(${{ parameters.enableAADProfile }})
      inputs:
        azurePowerShellVersion: LatestVersion
        azureSubscription:  $(azureSubscriptionEndpoint)
        ScriptType: InlineScript
        Inline: |
          $subscriptionId = (Get-AzContext).Subscription.Id
          New-AzSubscriptionDeployment -Location '$(location)' -TemplateFile '$(Build.SourcesDirectory)/$(Build.Repository.Name)/bicep/main.bicep' -TemplateParameterObject @{
            subscriptionId = $subscriptionId
            location = '$(location)'
            prefix = '$(prefix)'
            contosoSH360ClusterResourceGroupName = '$(resourceGroupName)'
            opsResourceGroupName = '$(workspaceResourceGroupName)'
            logAnalyticsWorkspaceName = '$(workspaceName)'
            workspaceSkuName = '$(workspaceSkuName)'
            montioredClusterName = '$(AKSName)'
            nonMontioredClusterName = '$(NonMonitoredAKSName)'
            adminUser = '$(chVmAdminUser)'
            adminPassword = '$(chVmAdminPassword)'
            servicePrincipalClientId = '$(ContosoSH360ClusterSPClientId)'
            servicePrincipalClientSecret = '$(ContosoSH360ClusterSPClientSecret)'
            agentVMSize = '$(agentVMSize)'
            aksClusterNetworkPlugin = '$(aksClusterNetworkPlugin)'
            aksClusterNetworkPolicy = '$(aksClusterNetworkPolicy)'
            aksClusterServiceCidr = '$(aksClusterServiceCidr)'
            aksClusterDockerBridgeCidr = '$(aksClusterDockerBridgeCidr)'
            clusterVersion = '$(clusterVersion)'
            aadProfile = $[variables.aadProfile]
          } -Verbose

    - task: AzureCLI@2
      displayName: 'Enable MDM'
      #condition: false
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $cluster = az aks show -g '$(resourceGroupName)' -n '$(AKSName)' --output json
          $clusterData = $cluster | ConvertFrom-Json
          az role assignment create --assignee-object-id "$(ContosoSH360ClusterSPObjectId)" --scope $clusterData.id --role "Monitoring Metrics Publisher"

    - task: KubectlInstaller@0
      displayName: 'Install Kubectl latest'

    - task: Kubernetes@1
      displayName: 'kubectl apply invalidimage'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/invalidimage.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply ngnix-app'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/ngnix-app.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply minecraft-namespace'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/minecraft-namespace.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply minecraft3'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/minecraft3.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply minecraft3'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/ngnix-app.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply prometheus'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/prometheus.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply windows-service'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/windows-service.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply prometheus-bundle'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/$(Build.Repository.Name)/kubernetes-manifests/prometheus-bundle.yaml'