# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

trigger:
- none

parameters:
- name: environment
  displayName: 'Environment to deploy'
  type: string
  default: Integration
  values:
  - Integration
  - PreProd
  - Production

- name: prefix
  displayName: 'Prefix'
  type: string

variables:
- ${{ if eq(parameters.environment, 'Integration') }}:
  - template: container-monitoring-integration.variables.yml
- ${{ if eq(parameters.environment, 'Production') }}:
  - template: container-monitoring-production.variables.yml
- ${{ if eq(parameters.environment, 'PreProd') }}:
  - template: container-monitoring-preprod.variables.yml

- template: container-monitoring-variables.yml

- name: prefix
  value: ${{ parameters.prefix }}

- group: ContainerMonitoring-AprilJones

stages:
- stage: Lint
  displayName: LintCode
  jobs:
  - job: LintCode
    displayName: Lint Code
    steps:
    - script: |
          az bicep build --file $(Build.SourcesDirectory)/bicep/main.bicep
      displayName: 'Run Bicep linter'

- stage: SecurityTest
  displayName: Run Security Code Analysis scan
  jobs:
  - job: SecurityCodeAnalysisScans
    displayName:  Run Security Code Analysis Scans
    pool:
      vmImage: windows-latest
    
    steps:
    - checkout: self

    - task: AntiMalware@3
      inputs:
        FileDirPath: '$(Build.SourcesDirectory)'
        EnableServices: true

    - task: CredScan@3
      inputs:
        toolMajorVersion: Latest
        scanFolder: '$(Build.SourcesDirectory)'

    - task: Armory@2
      inputs:
        targetDirectory: '$(Build.SourcesDirectory)'
        targetFiles: 'f|**\*.json;-|.gdn\**;'

    - task: SdtReport@2
      inputs:
        GdnExportSarifFile: false
        GdnExportHtmlFile: true
        GdnExportAllTools: true

    - task: PublishSecurityAnalysisLogs@3
      inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        AllTools: true
        ToolLogsNotFoundAction: 'Standard'

    - task: PostAnalysis@2
      displayName: 'Post Analysis'
      inputs:
        GdnBreakAllTools: true

- stage: Validate
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: '$(azureSubscriptionEndpoint)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/bicep/main.bicep'
        deploymentMode: 'Validation'
        overrideParameters: >
          -location $(location)
          -prefix $(prefix)
          -contosoSH360ClusterResourceGroupName $(resourceGroupName)
          -logAnalyticsWorkspaceName $(workspaceName)
          -workspaceSkuName $(workspaceSkuName)
          -monitoredClusterName $(AKSName)
          -adminUser $(chVmAdminUser)
          -adminPassword $(chVmAdminPassword)
          -servicePrincipalClientId $(ContosoSH360ClusterSPClientId)
          -servicePrincipalClientSecret $(ContosoSH360ClusterSPClientSecret)
          -agentVMSize $(agentVMSize)
          -serviceCidr $(aksClusterServiceCidr)
          -dockerBridgeCidr $(aksClusterDockerBridgeCidr)

- stage: Preview
  jobs: 
  - job: PreviewAzureChanges
    displayName: Preview Azure changes
    steps:
    - task: AzurePowerShell@4
      name: RunWhatIf
      displayName: Run what-if
      inputs:
        azurePowerShellVersion: LatestVersion
        azureSubscription:  $(azureSubscriptionEndpoint)
        ScriptType: InlineScript
        Inline: |
          $subscriptionId = (Get-AzContext).Subscription.Id
          New-AzSubscriptionDeployment -Whatif -Location '$(location)' -TemplateFile '$(Build.SourcesDirectory)/bicep/main.bicep' -TemplateParameterObject @{
            location = '$(location)'
            prefix = '$(prefix)'
            contosoSH360ClusterResourceGroupName = '$(resourceGroupName)'
            logAnalyticsWorkspaceName = '$(workspaceName)'
            workspaceSkuName = '$(workspaceSkuName)'
            monitoredClusterName = '$(AKSName)'
            adminUser = '$(chVmAdminUser)'
            adminPassword = '$(chVmAdminPassword)'
            servicePrincipalClientId = '$(ContosoSH360ClusterSPClientId)'
            servicePrincipalClientSecret = '$(ContosoSH360ClusterSPClientSecret)'
            agentVMSize = '$(agentVMSize)'
            serviceCidr = '$(aksClusterServiceCidr)'
            dockerBridgeCidr = '$(aksClusterDockerBridgeCidr)'
          } -Verbose

- stage: BicepDeploy
  displayName: Deploy Infrastructure
  jobs:
  - job: Deploy
    displayName: Deploy Container Monitoring
    pool: 
      vmImage: ubuntu-latest
    
    variables:
    - template: container-monitoring-variables.yml
    
    steps:
    - checkout: self

    - task: AzurePowerShell@4
      displayName: 'Create resources'
      inputs:
        azurePowerShellVersion: LatestVersion
        azureSubscription:  $(azureSubscriptionEndpoint)
        ScriptType: InlineScript
        Inline: |
          $subscriptionId = (Get-AzContext).Subscription.Id
          New-AzSubscriptionDeployment -Location '$(location)' -TemplateFile '$(Build.SourcesDirectory)/bicep/main.bicep' -TemplateParameterObject @{
            location = '$(location)'
            prefix = '$(prefix)'
            contosoSH360ClusterResourceGroupName = '$(resourceGroupName)'
            logAnalyticsWorkspaceName = '$(workspaceName)'
            workspaceSkuName = '$(workspaceSkuName)'
            monitoredClusterName = '$(AKSName)'
            adminUser = '$(chVmAdminUser)'
            adminPassword = '$(chVmAdminPassword)'
            servicePrincipalClientId = '$(ContosoSH360ClusterSPClientId)'
            servicePrincipalClientSecret = '$(ContosoSH360ClusterSPClientSecret)'
            agentVMSize = '$(agentVMSize)'
            serviceCidr = '$(aksClusterServiceCidr)'
            dockerBridgeCidr = '$(aksClusterDockerBridgeCidr)'
          } -Verbose

    - task: AzureCLI@2
      displayName: 'Cluster role assignment'
      #condition: false
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $cluster = az aks show -g '$(resourceGroupName)' -n '$(AKSName)' --output json
          $clusterData = $cluster | ConvertFrom-Json
          az role assignment create --assignee-object-id "$(ContosoSH360ClusterSPObjectId)" --scope $clusterData.id --role "Monitoring Metrics Publisher"

- stage: ApplicationDeployment
  displayName: Deploy Application
  jobs:
  - job: Deploy
    displayName: Deploy Manifests to Container Monitoring
    pool: 
      vmImage: ubuntu-latest
    
    variables:
    - template: container-monitoring-variables.yml
    
    steps:
    - checkout: self
    - task: KubectlInstaller@0
      displayName: 'Install Kubectl latest'

    - task: Kubernetes@1
      displayName: 'kubectl apply azure-vote-namespace'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/kubernetes-manifests/azure-vote-namespace.yaml'

    - task: Kubernetes@1
      displayName: 'kubectl apply azure-vote running'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/kubernetes-manifests/azure-vote-running.yaml'
    
    - task: PowerShell@2
      displayName: wait for a minute
      inputs:
        targetType: 'inline'
        script: 'Start-Sleep -s 60'
    
    - task: Kubernetes@1
      displayName: 'kubectl apply azure-vote pending'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: '$(resourceGroupName)'
        kubernetesCluster: '$(AKSName)'
        command: apply
        arguments: '-f $(ContosoSH360ClusterFolder)/kubernetes-manifests/azure-vote-pending.yaml'