# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

variables:
- name: prefix
  value: '<name prefix>'
- name: suffix
  value: '<name suffix>'
- name: azureSubscriptionEndpoint
  value: '<ADO service connection name>'
- name: location
  value: <Azure region>
