apiVersion: extensions/v1
kind: DaemonSet
metadata:
 name: omsagent-private-preview-windows
 namespace: kube-system
spec:
 updateStrategy:
  type: RollingUpdate
 template:
  metadata:
   labels:
    dsName: "omsagent-private-preview-windows-ds"
  spec:
   serviceAccountName: omsagent
   containers:
     - name: omsagent-private-preview-windows 
       image: mcr.microsoft.com/azuremonitor/containerinsights/cidev:windowsprivatepreview03132020_2
       imagePullPolicy: Always
       resources:
        limits:
         cpu: 150m
         memory: 600Mi
        requests:
         cpu: 75m
         memory: 225Mi
       env:       
       - name: CI_WSID
         value: "57b62b14-2020-4fbe-af15-634b3f4b9aa0"
       - name: CI_SHARED_KEY
         value: "qrNGRYzbmpg7Zb40RUUwOYSiErnqZZf0aqQC5986uhHaCIEKNym90R3sLkQFEEy2z3rxWdFVf6pSgIvvnn/Oug=="
       - name: AKS_RESOURCE_ID
         value: "/subscriptions/e045cc0b-0eea-47e8-9176-28c8d2c109ac/resourcegroups/CH-ContosoSH360ClusterRG-Dev/providers/Microsoft.ContainerService/managedClusters/CH-ContosoSH360Cluster-Dev"
       - name: AKS_REGION
         value: "East US"
       - name: CONTROLLER_TYPE
         value: "DaemonSet"
       - name: CI_DOMAIN
         value: "opinsights.azure.com"
       - name: CI_CRT_LOCATION
         value: "C://oms.crt"
       - name: CI_KEY_LOCATION
         value: "C://oms.key"
       - name: CI_NODE_IP
         valueFrom:
            fieldRef:
              fieldPath: status.hostIP
       - name: CI_HOSTNAME
         valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
       - name: APPLICATIONINSIGHTS_AUTH
         value: "NzAwZGM5OGYtYTdhZC00NThkLWI5NWMtMjA3ZjM3NmM3YmRi"
       volumeMounts:
        - mountPath: \\.\pipe\docker_engine
          name: docker-engine-pipe  
        - mountPath: C:\ProgramData\docker\containers
          name: docker-windows-docker-containers
        - mountPath: C:\var
          name: docker-windows-kuberenetes-container-logs
        - mountPath: C:\host
          name: docker-windows-host
   nodeSelector:
    beta.kubernetes.io/os: windows    
   # Tolerate a NoSchedule taint on master that ACS Engine sets.
   tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
   volumes:
     - name: docker-engine-pipe 
       hostPath:
         path: \\.\pipe\docker_engine
         type: null
     - name: docker-windows-kuberenetes-container-logs
       hostPath:
         path: C:\var
     - name: docker-windows-docker-containers
       hostPath:
         path: C:\ProgramData\docker\containers
     - name: docker-windows-host
       hostPath:
         path: C:\
     